apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  # Kubernetes lo codificará internamente. Usa las mismas de tu docker-compose
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: incidents_db